<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class EventSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events = [
            [
                'title' => 'Jakarta Marathon 2025',
                'description' => 'Marathon internasional terbesar di Jakarta dengan rute melalui landmark-landmark terkenal kota. Tersedia kategori 5K, 10K, Half Marathon, dan Full Marathon untuk semua level pelari.',
                'image' => 'jakarta-marathon.jpg',
                'start_date' => Carbon::now()->addMonths(2)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addMonths(2)->addHours(8)->format('Y-m-d H:i:s'),
                'location' => 'Bundaran HI, Jakarta Pusat',
                'price' => 250000.00,
                'max_participants' => 15000,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Badminton Tournament Yogyakarta Open',
                'description' => 'Turnamen bulu tangkis tingkat nasional dengan hadiah jutaan rupiah. Kategori tunggal putra, tunggal putri, ganda putra, ganda putri, dan ganda campuran.',
                'image' => 'badminton-tournament.jpg',
                'start_date' => Carbon::now()->addDays(45)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(47)->addHours(10)->format('Y-m-d H:i:s'),
                'location' => 'GOR Among Raga, Yogyakarta',
                'price' => 150000.00,
                'max_participants' => 200,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Fun Bike Borobudur Heritage',
                'description' => 'Sepeda santai menyusuri keindahan Candi Borobudur dan sekitarnya. Cocok untuk keluarga dengan pemandangan sunrise yang menakjubkan.',
                'image' => 'fun-bike-borobudur.jpg',
                'start_date' => Carbon::now()->addDays(30)->setTime(5, 30)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(30)->setTime(10, 0)->format('Y-m-d H:i:s'),
                'location' => 'Taman Lumbini, Borobudur',
                'price' => 75000.00,
                'max_participants' => 500,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Swimming Competition Aquatic Center',
                'description' => 'Kompetisi renang untuk berbagai kategori usia mulai dari anak-anak hingga dewasa. Gaya bebas, gaya punggung, gaya dada, dan gaya kupu-kupu.',
                'image' => 'swimming-competition.jpg',
                'start_date' => Carbon::now()->addDays(60)->setTime(8, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(60)->setTime(17, 0)->format('Y-m-d H:i:s'),
                'location' => 'Gelora Bung Karno Aquatic Center',
                'price' => 100000.00,
                'max_participants' => 300,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Basketball 3x3 Street Tournament',
                'description' => 'Turnamen basket jalanan 3 lawan 3 dengan sistem knockout. Terbuka untuk semua usia dengan kategori junior dan senior.',
                'image' => 'basketball-3x3.jpg',
                'start_date' => Carbon::now()->addWeeks(3)->setTime(14, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addWeeks(3)->setTime(20, 0)->format('Y-m-d H:i:s'),
                'location' => 'Lapangan Basket Senayan',
                'price' => 200000.00,
                'max_participants' => 64,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Yoga Festival Bali Retreat',
                'description' => 'Festival yoga 3 hari 2 malam di Bali dengan instruktur internasional. Termasuk akomodasi, makan, dan sesi meditasi di pantai.',
                'image' => 'yoga-festival-bali.jpg',
                'start_date' => Carbon::now()->addMonths(3)->setTime(6, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addMonths(3)->addDays(2)->setTime(18, 0)->format('Y-m-d H:i:s'),
                'location' => 'Ubud, Bali',
                'price' => 1500000.00,
                'max_participants' => 50,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Football (Soccer) League Championship',
                'description' => 'Liga sepak bola amatir dengan sistem kompetisi penuh. Pertandingan berlangsung setiap weekend selama 3 bulan.',
                'image' => 'football-league.jpg',
                'start_date' => Carbon::now()->addMonth()->setTime(15, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addMonths(4)->setTime(18, 0)->format('Y-m-d H:i:s'),
                'location' => 'Stadion Mini Kuningan',
                'price' => 2000000.00,
                'max_participants' => 16,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Rock Climbing Adventure',
                'description' => 'Petualangan panjat tebing untuk pemula hingga mahir. Peralatan lengkap disediakan, dipandu oleh instruktur bersertifikat.',
                'image' => 'rock-climbing.jpg',
                'start_date' => Carbon::now()->addDays(20)->setTime(7, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(20)->setTime(16, 0)->format('Y-m-d H:i:s'),
                'location' => 'Gunung Parang, Purwakarta',
                'price' => 350000.00,
                'max_participants' => 30,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Volleyball Beach Tournament',
                'description' => 'Turnamen voli pantai 2 lawan 2 di pantai Ancol. Suasana santai dengan hadiah menarik untuk para juara.',
                'image' => 'beach-volleyball.jpg',
                'start_date' => Carbon::now()->addDays(35)->setTime(8, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(35)->setTime(17, 0)->format('Y-m-d H:i:s'),
                'location' => 'Pantai Ancol, Jakarta Utara',
                'price' => 120000.00,
                'max_participants' => 32,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Triathlon Sprint Challenge',
                'description' => 'Kompetisi triathlon jarak sprint: berenang 750m, bersepeda 20km, dan lari 5km. Untuk atlet yang ingin merasakan tantangan triathlon.',
                'image' => 'triathlon-sprint.jpg',
                'start_date' => Carbon::now()->addMonths(4)->setTime(6, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addMonths(4)->setTime(12, 0)->format('Y-m-d H:i:s'),
                'location' => 'Danau Sunter, Jakarta Utara',
                'price' => 400000.00,
                'max_participants' => 150,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Table Tennis Championship',
                'description' => 'Kejuaraan tenis meja tingkat kota dengan kategori pemula, menengah, dan mahir. Sistem gugur dengan babak penyisihan.',
                'image' => 'table-tennis.jpg',
                'start_date' => Carbon::now()->addDays(50)->setTime(9, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(51)->setTime(18, 0)->format('Y-m-d H:i:s'),
                'location' => 'GOR Soemantri Brodjonegoro',
                'price' => 80000.00,
                'max_participants' => 128,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'title' => 'Hiking Adventure Gunung Gede',
                'description' => 'Pendakian gunung bersama komunitas dengan guide berpengalaman. Termasuk transportasi, makan, dan peralatan camping.',
                'image' => 'hiking-gunung-gede.jpg',
                'start_date' => Carbon::now()->addDays(40)->setTime(4, 0)->format('Y-m-d H:i:s'),
                'end_date' => Carbon::now()->addDays(41)->setTime(20, 0)->format('Y-m-d H:i:s'),
                'location' => 'Gunung Gede Pangrango, Bogor',
                'price' => 300000.00,
                'max_participants' => 25,
                'status' => 'active',
                'registrations' => json_encode([]),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('events')->insert($events);
    }
}
